package edu.poly.common;


//enum la kieu du lieu liet ke

public enum PageType {
	USER_MANAGEMENT_PAGE,REPORT_MANAGEMENT_PAGE, VIDEO_MANAGEMENT_PAGE,
	USER_HOME_PAGE, USER_LOGIN_PAGE,USER_REGIST_PAGE,USER_CHANGEPASS_PAGE,USER_EDITPROFILE_PAGE,
	USER_FAVORITE_PAGE, REPORT_FAVORITE_COUNT, FIND_VIDEOS
}
